### ISSUE TITLE
Missing types.ts files in @dbml/parse@3.8.0

### ISSUE THREAD

**Issue by Alfoussen** [holistics/dbml#631] opened 2024-09-06 10:13 UTC
Hi,

Some files are absent from @dbml/parse@3.8.0, failing the typescript compilation

```typescript
import { Parser } from '@dbml/core';
```

```shell
$ npx tsc -b 

node_modules/@dbml/parse/dist/lib/lexer/tokens.d.ts:1:26 - error TS2307: Cannot find module '../types' or its corresponding type declarations.

1 import { Position } from '../types';
                           ~~~~~~~~~~

node_modules/@dbml/parse/dist/lib/parser/nodes.d.ts:3:26 - error TS2307: Cannot find module '../types' or its corresponding type declarations.

3 import { Position } from '../types';
                           ~~~~~~~~~~

node_modules/@dbml/parse/dist/compiler.d.ts:8:26 - error TS2307: Cannot find module './lib/interpreter/types' or its corresponding type declarations.

8 import { Database } from './lib/interpreter/types';
```

<img width="590" alt="image" src="https://github.com/user-attachments/assets/d65220b1-66fc-44b4-b1b7-c051010a1be6">

**Comment by huyleminh01** [comment] 2024-09-06 10:56
Hi @Alfoussen ,

Could you provide use with more information about your current situation?

- Typescript version
- Your `tsconfig.json` (if possible)

Thank you.

**Comment by Alfoussen** [comment] 2024-09-06 12:10
@huyleminh01 

Typescript : Version 5.5.4

tsconfig.json
```json
{
    "compilerOptions": {
      "module": "commonjs",
      "esModuleInterop": true,
      "target": "es6",
      "moduleResolution": "node",
      "sourceMap": true,
      "outDir": "dist"
    },
    "include": ["src/cli/**/*"],
    "exclude": ["**/*.spec.ts"],
    "lib": ["es2015"]
  }
```

**Comment by Alfoussen** [comment] 2024-09-07 05:46
Hi @huyleminh01 

I manually added those missing files named type.d.ts and could make it compile. I just wonder why they are absent (or suppressed) from the original package... I escalated back to some older versions and still same missing files. Let me know if you need more info.

**Comment by Huy-DNA** [comment] 2024-09-07 15:05
hi @Alfoussen, thanks for letting us know this :heart: We've acknowledged the problem and will notify you when the problem is fixed!

**Comment by Huy-DNA** [comment] 2024-09-15 13:34
@Alfoussen  fixed in https://github.com/holistics/dbml/pull/632, please let us know if you encounter any other errors.

**Closed by Huy-DNA** 2024-09-15 13:34 UTC
